version: '3'
services:

  web:
    image: services_webapp
    container_name: webapp
    ports:
      - "3000:3000"

  books:
    image: services_books
    container_name: books
    ports:
      - "3001:3001"
    depends_on:
      - "mongo"
    environment:
      - PORT=3001
      - APP_NAME=BooksApp
      - MONGO_DB_URL=mongodb://mongo/booksservice

  customers:
    image: services_customers
    container_name: customers
    ports:
      - "3002:3002"
    depends_on:
      - "mongo"
    environment:
      - PORT=3002
      - APP_NAME=CustomersApp
      - MONGO_DB_URL=mongodb://mongo/customersservice

  orders:
    image: services_orders
    container_name: orders
    ports:
      - "3003:3003"
    depends_on:
      - "mongo"
    environment:
      - BOOKS_URI=http://books:3001
      - CUSTOMERS_URI=http://customers:3002
      - PORT=3003
      - APP_NAME=OrdersApp
      - MONGO_DB_URL=mongodb://mongo/ordersservice

  mongo:
    image: "mongo"
    container_name: mongodb
    ports:
      - "27017:27017"

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./web/public:/srv/www/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
    depends_on:
      - web
      - books
      - customers
      - orders

  #mongoclient:
  #  image: mongoclient/mongoclient
  #  container_name: mongo_client
  #  depends_on:
  #    - "mongo"
  #  ports:
  #    - "4000:3000"

  #mongo-express:
  #  image: mongo-express
  #  container_name: mongo_express
  #  depends_on:
  #    - "mongo"
  #  ports:
  #   - "8081:8081"
  #  environment:
  #    - ME_CONFIG_MONGODB_SERVER=mongo
  #    - ME_CONFIG_BASICAUTH_USERNAME=admin
  #    - ME_CONFIG_BASICAUTH_PASSWORD=password

  #mongo-compass:
  #  image: marmelab/compass
  #  container_name: mongo_compass
  #  depends_on:
  #    - "mongo"
    
